// <auto-generated />
namespace Fitnessapp.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class UserTracker : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(UserTracker));
        
        string IMigrationMetadata.Id
        {
            get { return "202111221537522_UserTracker"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
